# UI translations
TRANSLATIONS = {
    "English": {
        # Main app
        "app_title": "词汇学习应用程序 - Vocabulary Learning App",
        "welcome_title": "🏠 Welcome to ZhSmart!",
        "welcome_subtitle": "Your Comprehensive Chinese Learning Companion",
        "welcome_description": "**ZhSmart** is designed to help you master Chinese vocabulary through interactive practice and comprehensive review tools.",
        "what_you_can_do": "🎯 What you can do:",
        "vocabulary_review_title": "📚 Vocabulary Review",
        "vocabulary_review_desc": "- Browse and search through the complete vocabulary database\n- View statistics and progress metrics\n- Take quick quizzes to test your knowledge\n- Filter vocabulary by level and lecture",
        "practice_mode_title": "🎮 Practice Mode",
        "practice_mode_desc": "- Interactive vocabulary practice sessions\n- Practice by specific levels or lectures\n- Get instant feedback on pronunciation and meaning\n- Track your progress and scores",
        "getting_started": "🚀 Getting Started",
        "getting_started_steps": "1. **Choose your preferred language** from the sidebar\n2. **Select a page** to start learning\n3. **Practice regularly** to improve your Chinese skills",
        "quick_stats": "📊 Quick Stats",
        "learning_modes": "Learning Modes",
        "languages": "Languages",
        "features": "Features",
        "tips_for_success": "💡 Tips for Success",
        "practice_regularly": "- **Practice regularly**: Even 10-15 minutes daily can make a big difference",
        "use_both_modes": "- **Use both modes**: Combine review and practice for best results",
        "focus_pronunciation": "- **Focus on pronunciation**: Pay attention to pinyin and tones",
        "review_mistakes": "- **Review mistakes**: Learn from incorrect answers to improve",
        "ready_to_start": "**Ready to start? Select a page from the sidebar! 🎉**",
        
        # Navigation
        "choose_page": "Choose a page:",
        "home": "🏠 Home",
        "vocabulary_review": "📚 Vocabulary Review",
        "practice_mode": "🎮 Practice Mode",
        "select_language": "Select Language:",
        "english": "English",
        "vietnamese": "Tiếng Việt",
        
        # Support
        "support": "📞 Support",
        "report_bug": "Report Bug",
        "update_words": "Update Words",
        "made_with_love": "Made with ❤️ for Chinese learners",
        
        # Practice mode
        "paritce_mode_title": "Practice Mode",
        "review_mode_title": "Review Mode",
        "select_range": "Select vocabulary range:",
        "all_vocab": "All Vocabularys",
        "by_levels": "By Levels",
        "by_lectures": "By Lectures",
        "choose_level": "Choose Level:",
        "choose_lecture": "Choose Lecture:",
        "from": "(From)",
        "to": "(To)",
        "num_words": "Number of available words:",
        "num_questions": "Number of questions:",
        "start_practice": "Start New Practice Session",
        "question": "Question",
        "of": "of",
        "chinese_char": "Chinese Character:",
        "enter_pinyin": "Enter the Pinyin:",
        "enter_meaning": "Enter the Meaning:",
        "check_answer": "Check Answer",
        "next_question": "Next Question",
        "change_range": "Change Vocabulary Range",
        "correct_pinyin": "Correct Pinyin:",
        "your_pinyin": "Your Pinyin accuracy:",
        "correct_meaning": "Correct Meaning:",
        "your_meaning": "Your Meaning accuracy:",
        "learn_more": "Learn more about '{}' on Hanzii",
        "outstanding": """
        🌟 Outstanding Performance! 🌟
        Your average accuracy: {score:.1f}%
        Keep up the excellent work! You've mastered these words.""",
        "good_progress": """
        🔸 Good Progress! 🔸
        Your average accuracy: {score:.1f}%
        You're on the right track, but there's room for improvement.""",
        "keep_practicing": """
        📚 Keep Practicing! 📚
        Your average accuracy: {score:.1f}%
        Don't give up! Regular practice will help you improve.""",
        "start_new": "Start New Session",
        "update_word": "Provide your own data here.",
        "not_enough_words": "This lecture does not have enough words. Please choose another lecture!",
        "practice_complete": "Practice Complete!",
        "final_score": "Final Score:",
        "excellent": "Excellent!",
        "good_job": "Good job!",
        "keep_practicing_final": "Keep practicing!",
        "questions_answered": "Questions answered:",
        "total_score": "Total score:",
        "start_new_practice": "Start New Practice",
        "question_score": "Question Score:",
        
        # Vocabulary Review
        "vocabulary_review_header": "📚 HSK Vocabulary Review and Practice",
        "vocabulary_review_welcome": "### Welcome to HSK Vocabulary Review! 📖",
        "vocabulary_review_description": "This page helps you review and explore Chinese vocabulary by HSK levels with examples.",
        "practice_tab": "Practice",
        "review_tab": "Review",
        "search_vocabulary": "Search Vocabulary",
        "filter_by_level": "Filter by HSK Level:",
        "search_placeholder": "Search by Chinese character, pinyin, or meaning:",
        "all": "All",
        "results": "📋 Results",
        "words": "words",
        "previous": "⬅️ Previous",
        "next": "Next ➡️",
        "page": "Page",
        "of_pages": "of",
        "no_vocabulary_found": "No vocabulary found matching your search criteria.",
        "chinese": "Chinese:",
        "pinyin": "Pinyin:",
        "meaning": "Meaning:",
        "no_example": "No example available",
        "example_label": "Example:",
        "hsk_level": "HSK Level:",
        "learn_more_hanzii": "🔍 Learn more on Hanzii",
        "vocabulary_statistics": "📊 Vocabulary Statistics",
        "total_words": "Total Words",
        "hsk_levels": "HSK Levels",
        "avg_words_per_level": "Avg Words/Level",
        "with_examples": "With Examples",
        "words_by_hsk_level": "📈 Words by HSK Level",
        "results_header": "📊 Results",
        "example_header": "📝 Example",
        "learn_more_link": "🔍 Learn more",
        
        # Authentication
        "practice_mode_protected": "🔒 Locked function",
        "password_protected_message": "This page is currently not available for everyone.",
        "password_label": "Password:",
        "login_button": "Login",
        "access_granted": "✅ Access granted! You can now use Practice Mode.",
        "incorrect_password": "❌ Incorrect password. Please try again.",
        "password_hint": "💡 Hint: The password is related to the app name and year.",
        "logout_button": "🔓 Logout from Practice Mode",
    },
    "Tiếng Việt": {
        # Main app
        "app_title": "词汇学习应用程序 - Ứng dụng học từ vựng",
        "welcome_title": "🏠 Chào mừng đến với ZhSmart!",
        "welcome_subtitle": "Người bạn đồng hành học tiếng Trung toàn diện",
        "welcome_description": "**ZhSmart** được thiết kế để giúp bạn thành thạo từ vựng tiếng Trung thông qua luyện tập tương tác và công cụ ôn tập toàn diện.",
        "what_you_can_do": "🎯 Những gì bạn có thể làm:",
        "vocabulary_review_title": "📚 Ôn tập từ vựng",
        "vocabulary_review_desc": "- Duyệt và tìm kiếm trong cơ sở dữ liệu từ vựng đầy đủ\n- Xem thống kê và chỉ số tiến độ\n- Làm bài kiểm tra nhanh để kiểm tra kiến thức\n- Lọc từ vựng theo cấp độ và bài học",
        "practice_mode_title": "🎮 Chế độ luyện tập",
        "practice_mode_desc": "- Phiên luyện tập từ vựng tương tác\n- Luyện tập theo cấp độ hoặc bài học cụ thể\n- Nhận phản hồi tức thì về phát âm và nghĩa\n- Theo dõi tiến độ và điểm số",
        "getting_started": "🚀 Bắt đầu",
        "getting_started_steps": "1. **Chọn ngôn ngữ ưa thích** từ thanh bên\n2. **Chọn trang** để bắt đầu học\n3. **Luyện tập thường xuyên** để cải thiện kỹ năng tiếng Trung",
        "quick_stats": "📊 Thống kê nhanh",
        "learning_modes": "Chế độ học",
        "languages": "Ngôn ngữ",
        "features": "Tính năng",
        "tips_for_success": "💡 Lời khuyên để thành công",
        "practice_regularly": "- **Luyện tập thường xuyên**: Chỉ cần 10-15 phút mỗi ngày cũng tạo ra sự khác biệt lớn",
        "use_both_modes": "- **Sử dụng cả hai chế độ**: Kết hợp ôn tập và luyện tập để có kết quả tốt nhất",
        "focus_pronunciation": "- **Tập trung vào phát âm**: Chú ý đến pinyin và thanh điệu",
        "review_mistakes": "- **Ôn lại lỗi sai**: Học từ câu trả lời sai để cải thiện",
        "ready_to_start": "**Sẵn sàng bắt đầu? Chọn trang từ thanh bên! 🎉**",
        
        # Navigation
        "choose_page": "Chọn trang:",
        "home": "🏠 Trang chủ",
        "vocabulary_review": "📚 Ôn tập từ vựng",
        "practice_mode": "🎮 Chế độ luyện tập",
        "select_language": "Chọn ngôn ngữ:",
        "english": "English",
        "vietnamese": "Tiếng Việt",
        
        # Support
        "support": "📞 Hỗ trợ",
        "report_bug": "Báo lỗi",
        "update_words": "Cập nhật từ vựng",
        "made_with_love": "Được tạo với ❤️ cho người học tiếng Trung",
        
        # Practice mode
        "paritce_mode_title": "Chế Độ Luyện Tập",
        "review_mode_title": "Chế Độ Ôn Tập",
        "select_range": "Chọn phạm vi từ vựng:",
        "all_vocab": "Tất cả từ vựng",
        "by_levels": "Theo cấp độ",
        "by_lectures": "Theo bài học",
        "choose_level": "Chọn cấp độ:",
        "choose_lecture": "Chọn bài học:",
        "from": "(Từ)",
        "to": "(Đến)",
        "num_words": "Số từ vựng hiện có:",
        "num_questions": "Số câu hỏi:",
        "start_practice": "Bắt đầu phiên luyện tập mới",
        "question": "Câu hỏi",
        "of": "trong",
        "chinese_char": "Chữ Hán:",
        "enter_pinyin": "Nhập Pinyin:",
        "enter_meaning": "Nhập nghĩa:",
        "check_answer": "Kiểm tra",
        "next_question": "Câu tiếp theo",
        "change_range": "Đổi phạm vi từ vựng",
        "correct_pinyin": "Pinyin đúng:",
        "your_pinyin": "Độ chính xác Pinyin của bạn:",
        "correct_meaning": "Nghĩa đúng:",
        "your_meaning": "Độ chính xác nghĩa của bạn:",
        "learn_more": "Tìm hiểu thêm về '{}' trên Hanzii",
        "outstanding": """
        🌟 Thành tích xuất sắc! 🌟
        Độ chính xác trung bình: {score:.1f}%
        Tiếp tục phát huy! Bạn đã thành thạo những từ này.""",
        "good_progress": """
        🔸 Tiến bộ tốt! 🔸
        Độ chính xác trung bình: {score:.1f}%
        Bạn đang đi đúng hướng, hãy cố gắng hơn nữa.""",
        "keep_practicing": """
        📚 Tiếp tục luyện tập! 📚
        Độ chính xác trung bình: {score:.1f}%
        Đừng bỏ cuộc! Luyện tập thường xuyên sẽ giúp bạn tiến bộ.""",
        "start_new": "Bắt đầu phiên mới",
        "update_word": "Cung cấp từ học của bạn tại đây.",
        "not_enough_words": "Bài học này không có đủ từ vựng. Vui lòng chọn bài học khác!",
        "practice_complete": "Hoàn thành luyện tập!",
        "final_score": "Điểm tổng kết:",
        "excellent": "Xuất sắc!",
        "good_job": "Làm tốt!",
        "keep_practicing_final": "Tiếp tục luyện tập!",
        "questions_answered": "Số câu đã trả lời:",
        "total_score": "Tổng điểm:",
        "question_score": "Điểm câu hỏi:",
        "start_new_practice": "Bắt đầu luyện tập mới",
        
        # Vocabulary Review
        "vocabulary_review_header": "📚 Ôn luyện từ vựng HSK",
        "vocabulary_review_welcome": "### Chào mừng đến với Ôn tập từ vựng HSK! 📖",
        "vocabulary_review_description": "Trang này giúp bạn ôn tập và khám phá từ vựng tiếng Trung theo cấp độ HSK với các ví dụ.",
        "practice_tab": "Luyện tập",
        "review_tab": "Ôn tập",
        "search_vocabulary": "Tìm kiếm từ vựng",
        "filter_by_level": "Lọc theo cấp HSK:",
        "search_placeholder": "Tìm theo chữ Hán, pinyin hoặc nghĩa:",
        "all": "Tất cả",
        "results": "📋 Kết quả",
        "words": "từ",
        "previous": "⬅️ Trước",
        "next": "Tiếp ➡️",
        "page": "Trang",
        "of_pages": "trong",
        "no_vocabulary_found": "Không tìm thấy từ vựng phù hợp với tiêu chí tìm kiếm của bạn.",
        "chinese": "Chữ Hán:",
        "pinyin": "Pinyin:",
        "meaning": "Nghĩa:",
        "no_example": "Không có ví dụ",
        "example_label": "Ví dụ:",
        "hsk_level": "Cấp HSK:",
        "learn_more_hanzii": "🔍 Tìm hiểu thêm trên Hanzii",
        "vocabulary_statistics": "📊 Thống kê từ vựng",
        "total_words": "Tổng số từ",
        "hsk_levels": "Cấp HSK",
        "avg_words_per_level": "TB từ/cấp",
        "with_examples": "Có ví dụ",
        "words_by_hsk_level": "📈 Từ theo cấp HSK",
        "results_header": "📊 Kết quả",
        "example_header": "📝 Ví dụ",
        "learn_more_link": "🔍 Tìm hiểu thêm",
        
        # Authentication
        "practice_mode_protected": "🔒 Chức năng chưa mở",
        "password_protected_message": "Trang này hiện chưa mở với tất cả người dùng.",
        "password_label": "Mật khẩu:",
        "login_button": "Đăng nhập",
        "access_granted": "✅ Truy cập được cấp! Bạn có thể sử dụng Chế độ luyện tập.",
        "incorrect_password": "❌ Mật khẩu không đúng. Vui lòng thử lại.",
        "password_hint": "💡 Gợi ý: Mật khẩu liên quan đến tên ứng dụng và năm.",
        "logout_button": "🔓 Đăng xuất khỏi Practice Mode",
    }
}